name: Techfriendly Solutions
favicon: null
layout_spectrum: 0.8787139269988984
typography_spectrum: 0.21233855793252587
title: 'Technology Consultant   https://thegrid.ai//techfriendly-solutions'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70267004-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dc2424'
    - '#ffffff'
    - '#d47a72'
    - '#e79694'
    - '#f9b7b4'
  brandStrength: 0.48043701564893126
  lightness: 0.08463233103975654
  saturation: 0.9253335732501
  rhythmicContrast: 0.6057412785012275
purpose: []
